# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/act_dailygoal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import types_pb2 as protobuf_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/act_dailygoal.proto',
  package='data',
  syntax='proto2',
  serialized_pb=_b('\n\x1cprotobuf/act_dailygoal.proto\x12\x04\x64\x61ta\x1a\x14protobuf/types.proto\"G\n\x14PbActivityMetMinGoal\x12\x0c\n\x04goal\x18\x01 \x02(\x02\x12!\n\x19\x61\x63tivity_cutoff_threshold\x18\x02 \x01(\x02\"\x86\x01\n\x12PbPolarBalanceGoal\x12\x1b\n\nstart_date\x18\x01 \x02(\x0b\x32\x07.PbDate\x12\x15\n\rtarget_weight\x18\x02 \x01(\x02\x12\x1e\n\x16goal_duration_in_weeks\x18\x03 \x01(\r\x12\x1c\n\x14\x66raction_of_activity\x18\x04 \x01(\x02\"\xea\x02\n\x13PbDailyActivityGoal\x12?\n\tgoal_type\x18\x03 \x01(\x0e\x32,.data.PbDailyActivityGoal.PbActivityGoalType\x12\x38\n\x14\x61\x63tivity_metmin_goal\x18\x01 \x01(\x0b\x32\x1a.data.PbActivityMetMinGoal\x12(\n\rlast_modified\x18\x02 \x02(\x0b\x32\x11.PbSystemDateTime\x12\x34\n\x12polar_balance_goal\x18\x04 \x01(\x0b\x32\x18.data.PbPolarBalanceGoal\"x\n\x12PbActivityGoalType\x12 \n\x1c\x41\x43TIVITY_GOAL_DAILY_ACTIVITY\x10\x01\x12\x1d\n\x19\x41\x43TIVITY_GOAL_WEIGHT_LOSS\x10\x02\x12!\n\x1d\x41\x43TIVITY_GOAL_WEIGHT_MAINTAIN\x10\x03')
  ,
  dependencies=[protobuf_dot_types__pb2.DESCRIPTOR,])



_PBDAILYACTIVITYGOAL_PBACTIVITYGOALTYPE = _descriptor.EnumDescriptor(
  name='PbActivityGoalType',
  full_name='data.PbDailyActivityGoal.PbActivityGoalType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTIVITY_GOAL_DAILY_ACTIVITY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITY_GOAL_WEIGHT_LOSS', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITY_GOAL_WEIGHT_MAINTAIN', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=513,
  serialized_end=633,
)
_sym_db.RegisterEnumDescriptor(_PBDAILYACTIVITYGOAL_PBACTIVITYGOALTYPE)


_PBACTIVITYMETMINGOAL = _descriptor.Descriptor(
  name='PbActivityMetMinGoal',
  full_name='data.PbActivityMetMinGoal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal', full_name='data.PbActivityMetMinGoal.goal', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activity_cutoff_threshold', full_name='data.PbActivityMetMinGoal.activity_cutoff_threshold', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=131,
)


_PBPOLARBALANCEGOAL = _descriptor.Descriptor(
  name='PbPolarBalanceGoal',
  full_name='data.PbPolarBalanceGoal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_date', full_name='data.PbPolarBalanceGoal.start_date', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_weight', full_name='data.PbPolarBalanceGoal.target_weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goal_duration_in_weeks', full_name='data.PbPolarBalanceGoal.goal_duration_in_weeks', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fraction_of_activity', full_name='data.PbPolarBalanceGoal.fraction_of_activity', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=268,
)


_PBDAILYACTIVITYGOAL = _descriptor.Descriptor(
  name='PbDailyActivityGoal',
  full_name='data.PbDailyActivityGoal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal_type', full_name='data.PbDailyActivityGoal.goal_type', index=0,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activity_metmin_goal', full_name='data.PbDailyActivityGoal.activity_metmin_goal', index=1,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_modified', full_name='data.PbDailyActivityGoal.last_modified', index=2,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polar_balance_goal', full_name='data.PbDailyActivityGoal.polar_balance_goal', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PBDAILYACTIVITYGOAL_PBACTIVITYGOALTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=633,
)

_PBPOLARBALANCEGOAL.fields_by_name['start_date'].message_type = protobuf_dot_types__pb2._PBDATE
_PBDAILYACTIVITYGOAL.fields_by_name['goal_type'].enum_type = _PBDAILYACTIVITYGOAL_PBACTIVITYGOALTYPE
_PBDAILYACTIVITYGOAL.fields_by_name['activity_metmin_goal'].message_type = _PBACTIVITYMETMINGOAL
_PBDAILYACTIVITYGOAL.fields_by_name['last_modified'].message_type = protobuf_dot_types__pb2._PBSYSTEMDATETIME
_PBDAILYACTIVITYGOAL.fields_by_name['polar_balance_goal'].message_type = _PBPOLARBALANCEGOAL
_PBDAILYACTIVITYGOAL_PBACTIVITYGOALTYPE.containing_type = _PBDAILYACTIVITYGOAL
DESCRIPTOR.message_types_by_name['PbActivityMetMinGoal'] = _PBACTIVITYMETMINGOAL
DESCRIPTOR.message_types_by_name['PbPolarBalanceGoal'] = _PBPOLARBALANCEGOAL
DESCRIPTOR.message_types_by_name['PbDailyActivityGoal'] = _PBDAILYACTIVITYGOAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbActivityMetMinGoal = _reflection.GeneratedProtocolMessageType('PbActivityMetMinGoal', (_message.Message,), dict(
  DESCRIPTOR = _PBACTIVITYMETMINGOAL,
  __module__ = 'protobuf.act_dailygoal_pb2'
  # @@protoc_insertion_point(class_scope:data.PbActivityMetMinGoal)
  ))
_sym_db.RegisterMessage(PbActivityMetMinGoal)

PbPolarBalanceGoal = _reflection.GeneratedProtocolMessageType('PbPolarBalanceGoal', (_message.Message,), dict(
  DESCRIPTOR = _PBPOLARBALANCEGOAL,
  __module__ = 'protobuf.act_dailygoal_pb2'
  # @@protoc_insertion_point(class_scope:data.PbPolarBalanceGoal)
  ))
_sym_db.RegisterMessage(PbPolarBalanceGoal)

PbDailyActivityGoal = _reflection.GeneratedProtocolMessageType('PbDailyActivityGoal', (_message.Message,), dict(
  DESCRIPTOR = _PBDAILYACTIVITYGOAL,
  __module__ = 'protobuf.act_dailygoal_pb2'
  # @@protoc_insertion_point(class_scope:data.PbDailyActivityGoal)
  ))
_sym_db.RegisterMessage(PbDailyActivityGoal)


# @@protoc_insertion_point(module_scope)
