# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/syncinfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import types_pb2 as protobuf_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/syncinfo.proto',
  package='data',
  syntax='proto2',
  serialized_pb=_b('\n\x17protobuf/syncinfo.proto\x12\x04\x64\x61ta\x1a\x14protobuf/types.proto\"\x9c\x01\n\nPbSyncInfo\x12(\n\rlast_modified\x18\x01 \x02(\x0b\x32\x11.PbSystemDateTime\x12\x14\n\x0c\x63hanged_path\x18\x02 \x03(\t\x12,\n\x11last_synchronized\x18\x03 \x01(\x0b\x32\x11.PbSystemDateTime\x12 \n\x12\x66ull_sync_required\x18\x04 \x01(\x08:\x04true')
  ,
  dependencies=[protobuf_dot_types__pb2.DESCRIPTOR,])




_PBSYNCINFO = _descriptor.Descriptor(
  name='PbSyncInfo',
  full_name='data.PbSyncInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_modified', full_name='data.PbSyncInfo.last_modified', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='changed_path', full_name='data.PbSyncInfo.changed_path', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_synchronized', full_name='data.PbSyncInfo.last_synchronized', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='full_sync_required', full_name='data.PbSyncInfo.full_sync_required', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=212,
)

_PBSYNCINFO.fields_by_name['last_modified'].message_type = protobuf_dot_types__pb2._PBSYSTEMDATETIME
_PBSYNCINFO.fields_by_name['last_synchronized'].message_type = protobuf_dot_types__pb2._PBSYSTEMDATETIME
DESCRIPTOR.message_types_by_name['PbSyncInfo'] = _PBSYNCINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbSyncInfo = _reflection.GeneratedProtocolMessageType('PbSyncInfo', (_message.Message,), dict(
  DESCRIPTOR = _PBSYNCINFO,
  __module__ = 'protobuf.syncinfo_pb2'
  # @@protoc_insertion_point(class_scope:data.PbSyncInfo)
  ))
_sym_db.RegisterMessage(PbSyncInfo)


# @@protoc_insertion_point(module_scope)
